package com.example.kim.newadapter;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import android.widget.ImageView;
import android.widget.ListView;

import java.util.ArrayList;


public class MainActivity extends AppCompatActivity {

    private static final String TAG = "MainActivity";
private PersonListAdapter adapter;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Log.d(TAG, "onCreate: Started.");
        ListView mListView = (ListView) findViewById(R.id.listview);
        ImageView imageView = (ImageView) findViewById(R.id.image);


        //Create the Person objects
        Person john = new Person("John","12-20-1998","Male" ,"drawable://" + R.drawable.image1);
        Person steve = new Person("Steve","08-03-1987","Male","drawable://" + R.drawable.image2);
        Person kim = new Person("kim","11-15-2000","male","drawable://" + R.drawable.image3);
        Person shee = new Person("shee","07-02-1999","Female","drawable://" + R.drawable.image1);
        Person matt = new Person("Matt","03-29-2001","Male","drawable://" + R.drawable.image2);
        Person caro = new Person("caro","03-29-2001","FeMale","drawable://" + R.drawable.image3);
        Person josee = new Person("josee","03-29-2001","Male","drawable://" + R.drawable.image1);
        //Add the Person objects to an ArrayList
        ArrayList<Person> peopleList = new ArrayList<>();
        peopleList.add(john);
        peopleList.add(john);
        peopleList.add(steve);
        peopleList.add(kim);
        peopleList.add(shee);
        peopleList.add(matt);
        peopleList.add(caro);
        peopleList.add(josee);
        peopleList.add(john);
        peopleList.add(steve);
        peopleList.add(kim);
        peopleList.add(shee);
        peopleList.add(matt);
        peopleList.add(caro);
        peopleList.add(josee);
        peopleList.add(john);
        peopleList.add(steve);
        peopleList.add(kim);
        peopleList.add(shee);
        peopleList.add(matt);
        peopleList.add(caro);
        peopleList.add(josee);
        peopleList.add(john);
        peopleList.add(steve);
        peopleList.add(kim);
        peopleList.add(shee);
        peopleList.add(matt);
        peopleList.add(caro);
        peopleList.add(josee);
        peopleList.add(john);
        peopleList.add(steve);
        peopleList.add(kim);
        peopleList.add(shee);
        peopleList.add(matt);
        peopleList.add(caro);
        peopleList.add(josee);
        peopleList.add(john);
        peopleList.add(steve);
        peopleList.add(kim);
        peopleList.add(shee);
        peopleList.add(matt);
        peopleList.add(caro);
        peopleList.add(josee);
        peopleList.add(john);
        peopleList.add(steve);
        peopleList.add(kim);
        peopleList.add(shee);
        peopleList.add(matt);
        peopleList.add(caro);
        peopleList.add(josee);
        peopleList.add(john);
        peopleList.add(steve);
        peopleList.add(kim);
        peopleList.add(shee);
        peopleList.add(matt);
        peopleList.add(caro);
        peopleList.add(josee);
        peopleList.add(john);
        peopleList.add(steve);
        peopleList.add(kim);
        peopleList.add(shee);
        peopleList.add(matt);
        peopleList.add(caro);
        peopleList.add(josee);
        peopleList.add(john);
        peopleList.add(steve);
        peopleList.add(kim);
        peopleList.add(shee);
        peopleList.add(matt);
        peopleList.add(caro);
        peopleList.add(josee);
        peopleList.add(john);
        peopleList.add(steve);
        peopleList.add(kim);
        peopleList.add(shee);
        peopleList.add(matt);
        peopleList.add(caro);
        peopleList.add(josee);
        peopleList.add(john);
        peopleList.add(steve);
        peopleList.add(kim);
        peopleList.add(shee);
        peopleList.add(matt);
        peopleList.add(caro);
        peopleList.add(josee);
        peopleList.add(john);
        peopleList.add(steve);
        peopleList.add(kim);
        peopleList.add(shee);
        peopleList.add(matt);
        peopleList.add(caro);
        peopleList.add(josee);
        peopleList.add(john);
        peopleList.add(steve);
        peopleList.add(kim);
        peopleList.add(shee);
        peopleList.add(matt);
        peopleList.add(caro);
        peopleList.add(josee);
        peopleList.add(steve);
        peopleList.add(kim);
        peopleList.add(shee);
        peopleList.add(matt);
        peopleList.add(caro);
        peopleList.add(josee);
        peopleList.add(john);
        peopleList.add(steve);
        peopleList.add(kim);
        peopleList.add(shee);
        peopleList.add(matt);
        peopleList.add(caro);
        peopleList.add(josee);
        peopleList.add(john);
        peopleList.add(steve);
        peopleList.add(kim);
        peopleList.add(shee);
        peopleList.add(matt);
        peopleList.add(caro);
        peopleList.add(josee);
        peopleList.add(john);
        peopleList.add(steve);
        peopleList.add(kim);
        peopleList.add(shee);
        peopleList.add(matt);
        peopleList.add(caro);
        peopleList.add(josee);
        peopleList.add(john);
        peopleList.add(steve);
        peopleList.add(kim);
        peopleList.add(shee);
        peopleList.add(matt);
        peopleList.add(caro);
        peopleList.add(josee);
        peopleList.add(john);
        peopleList.add(steve);
        peopleList.add(kim);
        peopleList.add(shee);
        peopleList.add(matt);
        peopleList.add(caro);
        peopleList.add(josee);
        peopleList.add(john);
        peopleList.add(steve);
        peopleList.add(kim);
        peopleList.add(shee);
        peopleList.add(matt);
        peopleList.add(caro);
        peopleList.add(josee);

        adapter = new PersonListAdapter(this, R.layout.array_adapter_view, peopleList);
        mListView.setAdapter(adapter);

    }
}
